services:
  app:
    build: .
    container_name: shopy_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    env_file:
      - .env  # Load RDS credentials from .env
